services:
  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    restart: unless-stopped
    ports:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.it-tools.rule=Host(`it-tools.villa.emanueletessore.com`)
      - traefik.http.routers.it-tools.entrypoints=websecure
      - traefik.http.routers.it-tools.tls.certresolver=letsencrypt
      - traefik.docker.network=traefik-proxy
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true