services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    ports:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.villa.emanueletessore.com`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=letsencrypt
      - traefik.docker.network=traefik-proxy
    networks:
      - traefik-proxy

  test:
    image: nginx:latest
    container_name: test
    restart: unless-stopped
    ports:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.test.rule=Host(`test.villa.emanueletessore.com`)
      - traefik.http.routers.test.entrypoints=websecure
      - traefik.http.routers.test.tls.certresolver=letsencrypt
      - traefik.docker.network=traefik-proxy
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true